version: "3.1"
services:

    nginx:
      image: nginx:alpine
      container_name: docker-nginx
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "127.0.0.1:80:80"

    php-fpm:
      build: docker/php-fpm
      container_name: docker-php-fpm
      working_dir: /application
      volumes:
        - .:/application

    mysql:
      image: mysql:latest
      container_name: docker-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=sample
        - MYSQL_USER=sample
        - MYSQL_PASSWORD=sample
      ports:
        - "127.0.0.1:3306:3306"